// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/protocol.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientInfo struct {
	UID                  int32    `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	IP                   string   `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientInfo) Reset()         { *m = ClientInfo{} }
func (m *ClientInfo) String() string { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()    {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_87968d26f3046c60, []int{0}
}

func (m *ClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfo.Unmarshal(m, b)
}
func (m *ClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfo.Marshal(b, m, deterministic)
}
func (m *ClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfo.Merge(m, src)
}
func (m *ClientInfo) XXX_Size() int {
	return xxx_messageInfo_ClientInfo.Size(m)
}
func (m *ClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfo proto.InternalMessageInfo

func (m *ClientInfo) GetUID() int32 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *ClientInfo) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

type GsConnectInfo struct {
	GsId                 int32    `protobuf:"varint,1,opt,name=GsId,proto3" json:"GsId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GsConnectInfo) Reset()         { *m = GsConnectInfo{} }
func (m *GsConnectInfo) String() string { return proto.CompactTextString(m) }
func (*GsConnectInfo) ProtoMessage()    {}
func (*GsConnectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_87968d26f3046c60, []int{1}
}

func (m *GsConnectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GsConnectInfo.Unmarshal(m, b)
}
func (m *GsConnectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GsConnectInfo.Marshal(b, m, deterministic)
}
func (m *GsConnectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GsConnectInfo.Merge(m, src)
}
func (m *GsConnectInfo) XXX_Size() int {
	return xxx_messageInfo_GsConnectInfo.Size(m)
}
func (m *GsConnectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GsConnectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GsConnectInfo proto.InternalMessageInfo

func (m *GsConnectInfo) GetGsId() int32 {
	if m != nil {
		return m.GsId
	}
	return 0
}

type NullMsg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NullMsg) Reset()         { *m = NullMsg{} }
func (m *NullMsg) String() string { return proto.CompactTextString(m) }
func (*NullMsg) ProtoMessage()    {}
func (*NullMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_87968d26f3046c60, []int{2}
}

func (m *NullMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullMsg.Unmarshal(m, b)
}
func (m *NullMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullMsg.Marshal(b, m, deterministic)
}
func (m *NullMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullMsg.Merge(m, src)
}
func (m *NullMsg) XXX_Size() int {
	return xxx_messageInfo_NullMsg.Size(m)
}
func (m *NullMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NullMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NullMsg proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ClientInfo)(nil), "protocol.ClientInfo")
	proto.RegisterType((*GsConnectInfo)(nil), "protocol.GsConnectInfo")
	proto.RegisterType((*NullMsg)(nil), "protocol.NullMsg")
}

func init() { proto.RegisterFile("protocol/protocol.proto", fileDescriptor_87968d26f3046c60) }

var fileDescriptor_87968d26f3046c60 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x87, 0x31, 0xf4, 0xc0, 0x0c, 0x21, 0x0e, 0x18, 0x5f, 0x49, 0x8f,
	0x8b, 0xcb, 0x39, 0x27, 0x33, 0x35, 0xaf, 0xc4, 0x33, 0x2f, 0x2d, 0x5f, 0x48, 0x80, 0x8b, 0x39,
	0xd4, 0xd3, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x35, 0x08, 0xc4, 0x14, 0xe2, 0xe3, 0x62, 0xf2,
	0x0c, 0x90, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xf2, 0x0c, 0x50, 0x52, 0xe6, 0xe2, 0x75,
	0x2f, 0x76, 0xce, 0xcf, 0xcb, 0x4b, 0x4d, 0x86, 0x68, 0x11, 0xe2, 0x62, 0x71, 0x2f, 0xf6, 0x4c,
	0x81, 0xea, 0x01, 0xb3, 0x95, 0x38, 0xb9, 0xd8, 0xfd, 0x4a, 0x73, 0x72, 0x7c, 0x8b, 0xd3, 0x93,
	0xd8, 0xc0, 0x36, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x12, 0x06, 0x4a, 0x8b, 0x00,
	0x00, 0x00,
}
